# Add account settings and API keys here.
# This file should be listed in .gitignore to keep your settings secret!
# Each entry gets set as a local environment variable.

API_URI: ''
API_KEY: ''
SECTOR: 'medical'